server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    types {
        application/javascript mjs js;
        text/css css;
        text/html html;
        image/svg+xml svg;
        application/pdf pdf;
    }
    default_type application/octet-stream;
}
